# 백엔드용 Dockerfile

# 파이썬 베이스 이미지 사용
FROM python:3.9

# 작업 디렉토리 설정
WORKDIR /app

# 필요한 의존성 설치
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install python-multipart
RUN pip install uvicorn[standard]

# 백엔드 애플리케이션 코드 복사
COPY backend.py .

# 백엔드 애플리케이션 실행
CMD ["uvicorn", "backend:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]