version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    volumes:
      - ./:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    ports:
      - "3000:3000"
    depends_on:
      - backend
